include_guard(GLOBAL)

option(BUILD_WITH_MKL "Enable Intel oneMKL acceleration for Eigen" ON)
set(MKL_ROOT "" CACHE PATH "Path to the oneMKL installation root (optional)")
set(SMR_MKL_THREADING "AUTO" CACHE STRING "oneMKL threading layer (AUTO, sequential, gnu_thread, intel_thread, tbb_thread)")
set_property(CACHE SMR_MKL_THREADING PROPERTY STRINGS AUTO sequential gnu_thread intel_thread tbb_thread)
set(SMR_MKL_INTERFACE "lp64" CACHE STRING "oneMKL integer interface width")
set_property(CACHE SMR_MKL_INTERFACE PROPERTY STRINGS lp64 ilp64)

function(smr_default_mkl_threading out_var)
    if(CMAKE_CXX_COMPILER_ID MATCHES "Intel|IntelLLVM")
        set(${out_var} "intel_thread" PARENT_SCOPE)
    elseif(CMAKE_CXX_COMPILER_ID STREQUAL "GNU")
        set(${out_var} "gnu_thread" PARENT_SCOPE)
    else()
        set(${out_var} "sequential" PARENT_SCOPE)
    endif()
endfunction()

function(smr_mkl_config_dir_to_root config_dir out_var)
    if(IS_DIRECTORY "${config_dir}")
        get_filename_component(smr_mkl_config_dir "${config_dir}" REALPATH)
    else()
        get_filename_component(smr_mkl_config_dir "${config_dir}" DIRECTORY)
        get_filename_component(smr_mkl_config_dir "${smr_mkl_config_dir}" REALPATH)
    endif()
    get_filename_component(smr_mkl_root "${smr_mkl_config_dir}/../../../" ABSOLUTE)
    set(${out_var} "${smr_mkl_root}" PARENT_SCOPE)
endfunction()

function(smr_configure_mkl out_var)
    set(smr_use_mkl FALSE)

    if(BUILD_WITH_MKL)
        if(APPLE)
            message(STATUS "Eigen+oneMKL: disabled on macOS; falling back to Eigen's native backend")
        else()
            if(SMR_MKL_THREADING STREQUAL "AUTO")
                smr_default_mkl_threading(smr_selected_mkl_threading)
            else()
                set(smr_selected_mkl_threading "${SMR_MKL_THREADING}")
            endif()

            set(MKL_THREADING "${smr_selected_mkl_threading}")
            set(MKL_INTERFACE "${SMR_MKL_INTERFACE}")

            # Ensure MKL_ROOT
            if(NOT DEFINED MKL_ROOT OR "${MKL_ROOT}" STREQUAL "")
                if(DEFINED MKL_DIR AND NOT "${MKL_DIR}" STREQUAL "")
                    smr_mkl_config_dir_to_root("${MKL_DIR}" MKL_ROOT)
                endif()
            endif()

            # Find package
            set(smr_mkl_hints)
            if(DEFINED MKL_DIR AND NOT "${MKL_DIR}" STREQUAL "")
                list(APPEND smr_mkl_hints "${MKL_DIR}")
            endif()
            if(DEFINED MKL_ROOT AND NOT "${MKL_ROOT}" STREQUAL "")
                list(APPEND smr_mkl_hints "${MKL_ROOT}" "${MKL_ROOT}/lib/cmake/mkl")
            endif()
            if(UNIX AND NOT APPLE)
                list(APPEND smr_mkl_hints "/opt/intel/oneapi/mkl/latest" "/opt/intel/oneapi/mkl/latest/lib/cmake/mkl")
            endif()

            if(SMR_VERBOSE_CONFIGURE)
                if(DEFINED MKL_DIR AND NOT "${MKL_DIR}" STREQUAL "")
                    message(STATUS "MKL_DIR: ${MKL_DIR}")
                endif()
                if(DEFINED MKL_ROOT AND NOT "${MKL_ROOT}" STREQUAL "")
                    message(STATUS "MKL_ROOT preset: ${MKL_ROOT}")
                endif()
                message(STATUS "MKL search hints: ${smr_mkl_hints}")
            endif()

            find_package(MKL CONFIG REQUIRED HINTS ${smr_mkl_hints})
            set(smr_use_mkl TRUE)
            message(STATUS "Eigen+oneMKL: enabled (threading=${MKL_THREADING}, interface=${MKL_INTERFACE})")
        endif()
    else()
        message(STATUS "Eigen+oneMKL: disabled")
    endif()

    set(${out_var} "${smr_use_mkl}" PARENT_SCOPE)
endfunction()

function(smr_target_enable_mkl target_name)
    if(NOT TARGET "${target_name}")
        message(FATAL_ERROR "smr_target_enable_mkl: target '${target_name}' does not exist.")
    endif()

    target_link_libraries(${target_name} MKL::MKL)
    target_compile_definitions(${target_name} PRIVATE EIGEN_USE_MKL_ALL)

    if(CMAKE_CXX_COMPILER_ID MATCHES "GNU|Clang|AppleClang")
        target_compile_options(${target_name} PRIVATE -fpermissive)
    endif()
endfunction()
